### ISSUE TITLE
Icon for skipped splits

### ISSUE THREAD

**Issue by chlorate** [Komarulon/LiveSplit.GradedSplits#12]
When you skip a split, it would be interesting if you could choose to hide the icon or maybe specify a different icon.

Currently, it looks like this if you skip a split:

![capture](https://user-images.githubusercontent.com/13109677/37870867-ceb804ea-2fb6-11e8-853d-8d887156aa1c.PNG)

So I skipped Solar and it doesn't make sense to show the best icon for that split since the time is unknown. For Chill, I think the time of both splits are combined, so that split doesn't have an accurate time.

Rough idea of how this could look:

![capture](https://user-images.githubusercontent.com/13109677/37870910-2523d538-2fb8-11e8-9e91-bb6dafea9421.PNG)

**Comment by Komarulon** [comment]
Added, will be in next release.
