### ISSUE TITLE
Shadow for non-graded icon is rendered when it shouldn't be

### ISSUE THREAD

**Issue by chlorate** [Komarulon/LiveSplit.GradedSplits#13]
I think this is what's happening here. I have graded icons set to "override live run and PB".

I currently have the 4-bars icon manually set. The graded icon is the 2-bars one, but the drop shadow is rendered as if the 4-bars icon is there:

![capture](https://user-images.githubusercontent.com/13109677/37870970-a00c3230-2fb9-11e8-8014-dd54643ad529.PNG)

If I change the manual icon to 2-bars, the drop shadow looks correct:

![splits](https://user-images.githubusercontent.com/13109677/37871033-3cb147a6-2fba-11e8-9de1-fa04f6bc7827.gif)

So it looks like the manual icon is hidden, but its shadow is not.

**Comment by Komarulon** [comment]
Fixed, will be in next release.
