### ISSUE TITLE
Skipped split disappears if you enable icon but don't set an image

### ISSUE THREAD

**Issue by chlorate** [Komarulon/LiveSplit.GradedSplits#16]
If you enable the skipped split icon but don't set an icon image, then skipping a split will make the split disappear from the main window (visually, until you reopen your splits). Seems like a null/unset image is only a problem with the skipped split icon; the other icons seem to handle this case.

Ran into this thinking I could enable the icon and it would be blank by default. Does work if an image is set though!

![image](https://user-images.githubusercontent.com/13109677/38178085-67cec710-35e1-11e8-9803-cadebba5e6a3.png)

![splits](https://user-images.githubusercontent.com/13109677/38177980-51eb358e-35df-11e8-8fca-32e91b833c4f.gif)

**Comment by Komarulon** [comment]
Completed in 1.0.2
