### ISSUE TITLE
Graded Splits does not update with newest LiveSplit

### ISSUE THREAD

**Issue by dyceron** [Komarulon/LiveSplit.GradedSplits#21]
The update window for LiveSplit pops up for a new version of Graded Splits, but hitting yes never confirmed the update, and it continues to ask. https://twitter.com/Dyceron/status/1229213447646273536

**Comment by Komarulon** [comment]
Fixed in https://github.com/Komarulon/LiveSplit.GradedSplits/releases/tag/1.0.3
Thanks for reporting!
